name: Hello World
on:
  push:
    branches:
      - main
    paths:
      - src  
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello $MY_NAME"
    env:
      MY_NAME: Moksh